package com.simoscal.android

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The app's half of the `analyze_logs` contract.
 *
 * Most of these run against **a fixture the engine itself produced**
 * (`src/test/resources/analysis_result.json`, regenerated by
 * `parity/gen_analysis_fixture.py`) rather than against JSON written by hand
 * here. That is the whole point of it: a hand-written fixture only ever proves
 * the parser agrees with the test author's memory of the wire format, which is
 * exactly the gap that hid a broken params contract from V7 until
 * [VerifiedParamsTest] (CR-20260815-01). If the engine's shape moves, this
 * fixture goes stale loudly instead of the app silently reading fields that are
 * no longer there.
 *
 * The hand-built cases below it cover what a real engine run cannot easily
 * produce on demand: absent keys, an unknown enum value, a plot with no data.
 */
class AnalysisModelTest {

    private fun fixture(): JSONObject {
        val stream = checkNotNull(javaClass.classLoader?.getResourceAsStream("analysis_result.json")) {
            "analysis_result.json is missing — regenerate it with parity/gen_analysis_fixture.py"
        }
        return JSONObject(stream.bufferedReader().use { it.readText() })
    }

    private fun report(): AnalysisReport = AnalysisReport.parse(fixture())

    // ------------------------------------------------------- the real payload

    @Test
    fun `parses the engine's own analyze_logs result`() {
        val report = report()
        // One synthetic CSV carrying two pulls separated by idle — the shape
        // `build_folder` writes, and a real capture often is one file too.
        assertEquals(1, report.logs.size)
        assertEquals(2, report.pulls.size)
        assertTrue("some checks must have run", report.ran.isNotEmpty())
        assertTrue("findings expected from the injected faults", report.findings.isNotEmpty())
        assertFalse("no bin was supplied to the fixture run", report.calResolved)
    }

    @Test
    fun `every plot in the inventory arrives with its copy`() {
        val report = report()
        assertEquals(
            listOf("boost", "ignition", "knock", "lambda", "rail_pressure", "turbo_heat", "wastegate"),
            report.plots.map { it.id },
        )
        report.plots.forEach { plot ->
            assertTrue("${plot.id} title", plot.title.isNotBlank())
            // The description and tip are the engine's, so the app and the
            // library's report describe a plot in the same words.
            assertTrue("${plot.id} description", plot.description.length > 30)
            assertTrue("${plot.id} tip", plot.tip.length > 30)
        }
    }

    @Test
    fun `plots are presented in alphabetical order`() {
        val ids = report().plots.map { it.id }
        assertEquals(ids.sorted(), ids)
    }

    @Test
    fun `a drawn panel carries real samples with matching x and y`() {
        val boost = report().plots.first { it.id == "boost" }
        assertTrue(boost.drawn)
        assertTrue(boost.drawablePanels.isNotEmpty())
        boost.drawablePanels.forEach { panel ->
            assertTrue(panel.series.isNotEmpty())
            panel.series.forEach { series ->
                series.segments.forEach { segment ->
                    assertEquals(segment.x.size, segment.y.size)
                    assertTrue(segment.size > 0)
                    assertTrue(segment.x.all { it.isFinite() })
                    assertTrue(segment.y.all { it.isFinite() })
                }
            }
        }
    }

    @Test
    fun `the boost plot carries a measured line and its dashed setpoint`() {
        // The pairing the screen's headline tip is about: solid measured against
        // dashed asked-for. If the roles stopped arriving, the tip would be
        // describing a plot that no longer has two kinds of line on it.
        val panel = report().plots.first { it.id == "boost" }
            .drawablePanels.first { it.series.any { s -> s.role == SeriesRole.REFERENCE } }
        assertTrue(panel.series.any { it.role == SeriesRole.PRIMARY })
        assertTrue(panel.series.any { it.role == SeriesRole.REFERENCE })
    }

    @Test
    fun `samples within a segment sweep one way in rpm`() {
        // The engine sorts each segment by x. A line drawn from unsorted samples
        // would zig-zag back across itself and read as noise that is not there.
        report().plots.flatMap { it.drawablePanels }.flatMap { it.series }
            .filter { it.role != SeriesRole.TRANSIENT }
            .flatMap { it.segments }
            .forEach { segment ->
                for (i in 1 until segment.size) {
                    assertTrue(
                        "segment must not step backwards in x",
                        segment.x[i] >= segment.x[i - 1],
                    )
                }
            }
    }

    @Test
    fun `colour slots agree across every plot for the same pull`() {
        // "The blue curve" has to be the same run everywhere, so a pull's ordinal
        // must not vary between plots.
        val byPull = mutableMapOf<Int, Int>()
        report().plots.flatMap { it.drawablePanels }.flatMap { it.series }
            .filter { it.role == SeriesRole.PRIMARY }
            .forEach { series ->
                val seen = byPull.put(series.pull, series.ordinal)
                if (seen != null) assertEquals(seen, series.ordinal)
            }
        assertTrue(byPull.isNotEmpty())
    }

    @Test
    fun `findings are grouped by severity and keep their evidence`() {
        val report = report()
        val high = report.findingsOf(Severity.HIGH)
        assertTrue("the injected faults should raise a High finding", high.isNotEmpty())
        assertTrue(high.all { it.severity == Severity.HIGH })
        assertTrue(high.any { it.evidence.isNotEmpty() })
        // Evidence keys come out sorted, so the same finding reads the same way twice.
        high.forEach { finding ->
            assertEquals(finding.evidence.map { it.first }.sorted(), finding.evidence.map { it.first })
        }
    }

    @Test
    fun `skipped checks name what they were missing`() {
        val skipped = report().skipped
        assertEquals(setOf("boost_cal", "boost_p0234"), skipped.map { it.checkId }.toSet())
        assertTrue(skipped.all { it.reason.isNotBlank() })
    }

    @Test
    fun `pull summaries carry gear and rpm span`() {
        report().pulls.forEach { pull ->
            assertTrue(pull.index > 0)
            assertTrue(pull.file.isNotBlank())
            assertTrue(pull.rpmMax > pull.rpmMin)
        }
    }

    @Test
    fun `display names survive the round trip`() {
        // The app's copy of a CSV is content-addressed, so its name on disk is a
        // hash. If the display name did not travel, every pull would be labelled
        // with 64 hex characters.
        report().logs.forEach { log ->
            assertTrue("log name should not be a bare hash", log.name.endsWith(".csv"))
        }
    }

    // ---------------------------------------------------- hand-built edge cases

    @Test
    fun `an empty result parses to an empty report rather than throwing`() {
        val report = AnalysisReport.parse(JSONObject())
        assertTrue(report.logs.isEmpty())
        assertTrue(report.plots.isEmpty())
        assertTrue(report.findings.isEmpty())
        assertFalse(report.calResolved)
    }

    @Test
    fun `an unknown severity is filed low rather than dropped`() {
        assertEquals(Severity.LOW, Severity.from("Catastrophic"))
        assertEquals(Severity.LOW, Severity.from(""))
        assertEquals(Severity.HIGH, Severity.from("High"))
        assertEquals(Severity.MEDIUM, Severity.from("medium"))
    }

    @Test
    fun `an unknown series role is treated as neutral, never as a measurement`() {
        // Mistaking a reference for a measured line is the error that would
        // actually mislead a reader, so the fallback leans the safe way.
        assertEquals(SeriesRole.SECONDARY, SeriesRole.from("something-new"))
        assertEquals(SeriesRole.PRIMARY, SeriesRole.from("primary"))
        assertEquals(SeriesRole.TRANSIENT, SeriesRole.from("transient"))
    }

    @Test
    fun `a plot the log had no data for is kept but not drawn`() {
        val json = JSONObject(
            """
            {"plots":[{"id":"turbo_heat","title":"Turbo speed","description":"d","tip":"t",
              "drawn":false,
              "panels":[{"title":"p","x_label":"rpm","y_label":"krpm","series":[],
                "thresholds":[{"value":190.0,"tone":"watch","label":"190k watch"}],
                "drawn":false}]}]}
            """.trimIndent()
        )
        val report = AnalysisReport.parse(json)
        // Kept, because an absent plot means an unlogged channel — not a
        // quantity that was fine. The screen names it rather than hiding it.
        assertEquals(1, report.plots.size)
        assertTrue(report.drawnPlots.isEmpty())
        assertEquals(1, report.undrawnPlots.size)
        // The thresholds are the spec's and still arrive; they never make it drawable.
        assertEquals(1, report.plots.first().panels.first().thresholds.size)
    }

    @Test
    fun `a panel claiming drawn with no series is not believed`() {
        val json = JSONObject(
            """
            {"plots":[{"id":"knock","title":"t","description":"d","tip":"x","drawn":true,
              "panels":[{"title":"p","series":[],"thresholds":[],"drawn":true}]}]}
            """.trimIndent()
        )
        // The screen would otherwise render an empty frame under a heading that
        // promised a measurement.
        assertFalse(AnalysisReport.parse(json).plots.first().drawn)
    }

    @Test
    fun `an empty segment is dropped so nothing draws a zero-length line`() {
        val json = JSONObject(
            """
            {"plots":[{"id":"knock","title":"t","description":"d","tip":"x","drawn":true,
              "panels":[{"title":"p","drawn":true,"thresholds":[],"series":[
                {"source":"min_knock","role":"primary","label":"","pull":1,"ordinal":0,
                 "segments":[{"x":[],"y":[]},{"x":[1000.0,2000.0],"y":[0.0,-1.0]}]}]}]}]}
            """.trimIndent()
        )
        val series = AnalysisReport.parse(json).plots.first().panels.first().series.first()
        assertEquals(1, series.segments.size)
        assertEquals(2, series.segments.first().size)
    }

    @Test
    fun `an unresolved gear stays null rather than defaulting to a wrong one`() {
        val json = JSONObject(
            """{"pulls":[{"index":1,"file":"a.csv","n_samples":40,"gear":null,
                 "rpm_min":2500.0,"rpm_max":6500.0,"duration_s":null}]}"""
        )
        val pull = AnalysisReport.parse(json).pulls.first()
        // A wrong gear on a pull summary is worse than an absent one — the whole
        // reason the engine reports gear resolution rather than guessing an offset.
        assertNull(pull.gear)
        assertNull(pull.durationSeconds)
        assertNotNull(pull.file)
    }
}
